---
- name: check mandatory variables
  fail:
    msg: 'variable {{ mandatory_var.key }} not defined'
  when: not mandatory_var.value
  loop: "{{ mandatory_vars | dict2items }}"
  loop_control:
    loop_var: mandatory_var

- name: pin {{ package_name }} version
  template:
    src: package.pref
    dest: /etc/apt/preferences.d/{{ package_name }}.pref
    owner: root
    group: root
    mode: "0640"
