---
- name: Converge
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    versions:
      bionic: "3.6.7-1~18.04"
      focal: "3.8.2-0ubuntu2"
      xenial: "3.5.1-3"
      buster: "3.7.3-1"
  roles:
    - role: pin-apt-package-version
      vars:
        package_name: python3
        package_version: "{{ versions[ansible_distribution_release] }}"
