---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: xenial
    image: ubuntu:xenial
  - name: bionic
    image: ubuntu:bionic
  - name: focal
    image: ubuntu:focal
  - name: buster
    image: debian:buster
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
