---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: xenial-role-pin-apt-package-version
    box: ubuntu/xenial64
  - name: bionic-role-pin-apt-package-version
    box: ubuntu/bionic64
  - name: buster-role-pin-apt-package-version
    box: debian/buster64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
