---
- name: Converge
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    pin_apt_packages_version_packages:
      - python3
  roles:
    - role: pin-apt-package-version
