---
- name: Converge
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: pin-apt-package-version
      vars:
        pin_apt_packages_version_packages:
          - python3
